<a href="https://colab.research.google.com/github/SRARNAB7/SRARNAB7/blob/main/Interview_Preparation_Feb_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
liver = pd.read_csv('https://hds5210-data.s3.amazonaws.com/indian_liver_patient.csv')

HTTPError: HTTP Error 403: Forbidden

In [ ]:
import pandas as pd
import requests
from io import StringIO

url = "https://hds5210-data.s3.amazonaws.com/indian_liver_patient.csv"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.raise_for_status()

liver = pd.read_csv(StringIO(response.text))

HTTPError: 403 Client Error: Forbidden for url: https://hds5210-data.s3.amazonaws.com/indian_liver_patient.csv

In [ ]:
liver.groupby('Gender').count()

In [ ]:
liver.groupby('Gender').count().reset_index()

In [ ]:
liver.groupby(['Gender','Age']).count().reset_index()

In [ ]:
liver['Decade'] = liver['Age']//10

In [ ]:
liver.groupby('Decade').count()

In [ ]:
def cms_ages(age):
  ranges = [
        {'min': 0,  'max': 18,  'label': 'A.  0-18'},
        {'min': 19, 'max': 44,  'label': 'B. 19-44'},
        {'min': 45, 'max': 64,  'label': 'C. 45-64'},
        {'min': 65, 'max': 84,  'label': 'D. 65-84'},
        {'min': 85, 'max': 999, 'label': 'E. 85-up'}
    ]

  for r in ranges:
    if age>= r.get('min') and age <= r.get('max'):
      return r.get('label')

  return 'Z.unknown'

In [ ]:
liver.set_index('Age').head()

In [ ]:
by_cms_age = liver.set_index('Age').groupby(cms_ages)

In [ ]:
by_cms_age.count().reset_index()

In [ ]:
grouped_liver = liver['Age'].describe()
grouped_liver

In [ ]:
grouped_liver = liver['Age'].mean()
grouped_liver

In [ ]:
grouped_liver = liver['Age'].agg(['mean','min'])

In [ ]:
liver.groupby('Gender').agg({'Age':['mean']})

In [ ]:
import pandas as pd

# Creating the first DataFrame
data1 = {
    'Patient_ID': [101, 102, 103],
    'Visit_Date': ['2024-12-01', '2024-12-02', '2024-12-03'],
    'Doctor': ['Dr. Smith', 'Dr. Adams', 'Dr. Lee']
}
df1 = pd.DataFrame(data1)

# Creating the second DataFrame
data2 = {
    'Patient_ID': [104, 105],
    'Visit_Date': ['2024-12-04', '2024-12-05'],
    'Doctor': ['Dr. Patel', 'Dr. Johnson']
}
df2 = pd.DataFrame(data2)

# Creating the third DataFrame
data3 = {
    'Patient_ID': [106, 107, 108],
    'Visit_Date': ['2024-12-06', '2024-12-07', '2024-12-08'],
    'Doctor': ['Dr. Carter', 'Dr. Davis', 'Dr. White']
}
df3 = pd.DataFrame(data3)

In [ ]:
concatened_df = pd.concat([df1,df2,df3])

In [ ]:
employees = pd.read_csv('https://hds5210-data.s3.amazonaws.com/employees.csv')
employees

HTTPError: HTTP Error 403: Forbidden

In [ ]:
departments = pd.read_csv('https://hds5210-data.s3.amazonaws.com/departments.csv')
departments

In [ ]:
total = departments.merge(employees,how ='outer',left_on ='Department',right_on ='Department')
total

In [ ]:
departments.merge(employees, how = 'left')

In [ ]:
import pandas as pd
data = pd.DataFrame([['a',1],['B',None],['C c',3]], columns=['letter','number'])
data

  letter  number
0      a     1.0
1      B     NaN
2    C c     3.0

In [ ]:
data['number'].fillna(0)

0    1.0
1    0.0
2    3.0
Name: number, dtype: float64

In [ ]:
data['number'].fillna(data['number'].mean())

0    1.0
1    2.0
2    3.0
Name: number, dtype: float64

In [ ]:
import pandas as pd
states = pd.DataFrame([
    ['1','AK',703423],
    [pd.NA, 'AL', 5634923],
    [pd.NA, 'AR', 3029341],
    [pd.NA, 'AZ', 2317412],
    ['2', 'CA', 13493821],
    [pd.NA, 'CO', 5434124]
], columns=['region','state','population'])

In [ ]:
states

  region state  population
0      1    AK      703423
1   <NA>    AL     5634923
2   <NA>    AR     3029341
3   <NA>    AZ     2317412
4      2    CA    13493821
5   <NA>    CO     5434124

In [ ]:
states['region'] = states['region'].fillna(states['state'])

Write a Python Program to Check Prime Number.

In [6]:
num = int(input("Enter the number"))

flag = False
if (num==1):
  print(f"{num}, is not a prime number")
elif num > 1:
  for i in range(2,num):
    if(num%i==0):
      flag = True
      break

if flag == True:
  print("It is not a prime number")
else:
  print("It is a prime number")

Enter the number7
It is a prime number

Write a Python program to find largest number in a list.

In [16]:
numbers = [30, 10, -45, 5, 20]

def largest_num(numbers):

  large = int()
  for num in  numbers:
    #large = int()
    if num > large:
      large = num

  print(f'The largest number is {large}')

In [17]:
numbers = [30, 10, -45, 5, 10]
largest_num(numbers)

The largest number is 30

Write a Python program to find second largest number in a list.

In [19]:
def second_largest(numbers):

  numbers.sort(reverse = True)
  second_largest = numbers[1]

  print(second_largest)

In [20]:
numbers = [23,5,66,87,91]
second_largest(numbers)

87

Write a Python program to print even numbers in a list.

In [21]:
def even_numbers(numbers):
  num = []

  for i in numbers:
    if i%2 == 0:
      num.append(i)

  print(num)

In [22]:
numbers = [2,6,9,4,0,1]
even_numbers(numbers)

[2, 6, 4, 0]

Write a Python program to Count occurrences of an element in a list.

In [23]:
my_list = [1, 2, 3, 4, 2, 5, 2, 3, 4, 6, 5]

def occurences(my_list):

  count_occur = {}

  for num in my_list:
    if num in count_occur:
      count_occur[num] +=1
    else:
      count_occur[num] = 1

  print(count_occur)

In [24]:
my_list = [1, 2, 3, 4, 2, 5, 2, 3, 4, 6, 5]
occurences(my_list)

{1: 1, 2: 3, 3: 2, 4: 2, 5: 2, 6: 1}